# Render.com 배포 설정
services:
  # FastAPI 백엔드
  - type: web
    name: playcat-chatbot-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USE_GEMINI
        value: true
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /api/health
    autoDeploy: true
