name: Keep Render Alive

on:
  schedule:
    # 5분마다 실행 (Render Free tier 15분 슬립 방지)
    - cron: '*/5 * * * *'
  workflow_dispatch:  # 수동 실행 가능

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: |
          echo "Pinging Render API..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://playcat-chatbot-api.onrender.com/api/health)
          echo "Response code: $response"
          if [ $response -eq 200 ]; then
            echo "✅ API is alive!"
          else
            echo "⚠️ API returned $response"
          fi
